apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-ace-rest-staging-1-dr
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://c111-e.us-east.containers.cloud.ibm.com:31784
  project: applications
  source:
    path: ace/environments/overlays/staging
    repoURL: https://github.com/iiab-mw-gitops/dr-cluster-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
